# Generated by Django 5.0.7 on 2024-08-05 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCombined',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_content', models.TextField()),
                ('improved_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentImproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='store/documents/improved')),
                ('status', models.CharField(default='improved', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='improved_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentOriginal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='store/document/original')),
                ('status', models.CharField(default='original', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AddField(
            model_name='documentcombined',
            name='improved_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improved_docs', to='documents.documentimproved'),
        ),
        migrations.AddField(
            model_name='documentcombined',
            name='original_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_docs', to='documents.documentoriginal'),
        ),
    ]
