# Generated by Django 5.0.7 on 2024-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documentcombined_documentimproved_documentoriginal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimproved',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='documentimproved',
            name='suggestion_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='documentimproved',
            name='document',
            field=models.FileField(upload_to='store/document/improved'),
        ),
    ]
