# Generated by Django 5.0.7 on 2024-08-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentimproved_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentimproved',
            name='user_id',
        ),
    ]
