# Generated by Django 5.0.7 on 2024-08-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_documentimproved_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentoriginal',
            old_name='user_id',
            new_name='user',
        ),
    ]
