# Generated by Django 5.0.7 on 2024-08-19 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_rename_user_id_documentoriginal_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcombined',
            name='improved_document',
        ),
        migrations.RemoveField(
            model_name='documentcombined',
            name='original_document',
        ),
    ]
